apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: {{ .Values.database.mongo.port }}
      targetPort: {{ .Values.database.mongo.port }}
  clusterIP: None  # Headless service for StatefulSet