apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque # basic secret type
stringData: # actual contents
  mongo-root-username: root
  mongo-root-password: example
  mongo-uri: mongodb://mongo-0.mongo:27017
