apiVersion: v1
kind: Service
metadata:
  name: mongodb-exporter
  labels:
    app: mongodb-exporter
spec:
  selector:
    app: mongodb-exporter
  ports:
    - protocol: TCP
      port: {{ .Values.metrics.Mongodb_exporter.mongodbExporter.port }}
      targetPort: {{ .Values.metrics.Mongodb_exporter.mongodbExporter.port }}
  type: LoadBalancer
