apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-config
data:
  datasource.yaml: | # Data source configuration
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        access: proxy
        # Access mode - proxy (server in the UI) or direct (browser in the UI).
        url: http://prometheus:9090
        editable: false
        isDefault: false
        uid: DS_PROMETHEUS
        jsonData:
          httpMethod: POST
          manageAlerts: true
          prometheusType: Prometheus
          prometheusVersion: 3.0.1
          cacheLevel: 'High'
          disableRecordingRules: false
          incrementalQueryOverlapWindow: 10m
  dashboards.yaml: | # Dashboard provisioning configuration
    apiVersion: 1

    providers:
      - name: 'default'
        folder: ''
        type: 'file'
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
data:
  {{- (.Files.Glob "files/20867_rev1.json").AsConfig | nindent 2 }}