apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque # basic secret type
stringData: # actual contents
  mongo-root-username: root
  mongo-root-password: example
  mongo-uri: mongodb://mongo-0.mongo:27017
  grafana-root-username: root
  grafana-root-password: example
  mdbExporterUsername: metrics
  mdbExporterPassword: example
  mdbExporterUri: mongodb://mongo-0.mongo:27017/admin